// Shell-guard codegen for build.rs.
//
// Parses config/shell_guard_policy.yaml into the compiled
// SHELL_PATTERNS table and validates config/shell_guard_policy_matrix.yaml
// against it (build fails on disagreement). The generated file contains
// ONLY the `pub const SHELL_PATTERNS: &[(&str, &str, &str, &str)]`
// literal (id, regex, hint, scope).

use std::env;
use std::fs;
use std::path::Path;

use serde::Deserialize;

fn default_scope() -> String {
    "both".to_string()
}

fn default_ctx() -> String {
    "command".to_string()
}

#[derive(Deserialize)]
struct ShellPolicyFile {
    #[serde(default = "crate::default_version")]
    _version: u32,
    patterns: Vec<ShellPattern>,
}

#[derive(Deserialize)]
struct ShellPattern {
    id: String,
    regex: String,
    hint: String,
    #[serde(default = "default_scope")]
    scope: String,
}

#[derive(Deserialize)]
struct ShellMatrixFile {
    #[serde(default = "crate::default_version")]
    _version: u32,
    cases: Vec<ShellMatrixCase>,
}

#[derive(Deserialize)]
struct ShellMatrixCase {
    id: String,
    #[allow(dead_code)]
    input: String,
    expect: String,
    rule: Option<String>,
    #[serde(default = "default_ctx")]
    #[allow(dead_code)]
    ctx: String,
}

pub fn emit_shell_guard_config(manifest: &Path, nofile_limit: u64) {
    let config_dir = manifest.join("config");
    let policy_text = fs::read_to_string(config_dir.join("shell_guard_policy.yaml"))
        .expect("build.rs: failed to read shell_guard_policy.yaml");
    let policy: ShellPolicyFile = serde_yaml::from_str(&policy_text)
        .expect("build.rs: failed to parse shell_guard_policy.yaml");
    let matrix_text = fs::read_to_string(config_dir.join("shell_guard_policy_matrix.yaml"))
        .expect("build.rs: failed to read shell_guard_policy_matrix.yaml");
    let matrix: ShellMatrixFile = serde_yaml::from_str(&matrix_text)
        .expect("build.rs: failed to parse shell_guard_policy_matrix.yaml");

    assert!(
        !policy.patterns.is_empty(),
        "build.rs: shell_guard_policy.yaml has no patterns"
    );
    let mut seen = std::collections::HashSet::new();
    for p in &policy.patterns {
        assert!(
            seen.insert(p.id.clone()),
            "build.rs: duplicate shell-guard pattern id {:?}",
            p.id
        );
        assert!(
            !p.regex.is_empty() && !p.hint.is_empty(),
            "build.rs: shell-guard pattern {:?} needs non-empty regex and hint",
            p.id
        );
        assert!(
            p.scope == "command"
                || p.scope == "script"
                || p.scope == "untrusted-script"
                || p.scope == "both",
            "build.rs: shell-guard pattern {:?} has invalid scope {:?} (command|script|untrusted-script|both)",
            p.id,
            p.scope
        );
        regex::bytes::Regex::new(&p.regex).unwrap_or_else(|e| {
            panic!(
                "build.rs: shell-guard pattern {:?} does not compile: {}",
                p.id, e
            )
        });
    }
    for case in &matrix.cases {
        assert!(
            case.expect == "blocked" || case.expect == "allowed",
            "build.rs: shell matrix case {:?} has invalid expect {:?}",
            case.id,
            case.expect
        );
        assert!(
            case.ctx == "command" || case.ctx == "script" || case.ctx == "untrusted-script",
            "build.rs: shell matrix case {:?} has invalid ctx {:?} (command|script)",
            case.id,
            case.ctx
        );
        if let Some(rule) = &case.rule {
            assert!(
                seen.contains(rule),
                "build.rs: shell matrix case {:?} references unknown rule {:?}",
                case.id,
                rule
            );
        }
    }
    for p in &policy.patterns {
        assert!(
            matrix.cases.iter().any(|c| {
                c.expect == "blocked"
                    && c.rule.as_deref() == Some(p.id.as_str())
                    && (p.scope == "both" || p.scope == c.ctx)
            }),
            "build.rs: shell-guard pattern {:?} has no blocked matrix case in a context its scope {:?} applies to",
            p.id,
            p.scope
        );
    }

    let mut code = String::from(
        "// Auto-generated by build.rs from config/shell_guard_policy.yaml. DO NOT EDIT.\n",
    );
    code.push_str("pub const SHELL_PATTERNS: &[(&str, &str, &str, &str)] = &[\n");
    for p in &policy.patterns {
        code.push_str(&format!(
            "    ({:?}, {:?}, {:?}, {:?}),\n",
            p.id, p.regex, p.hint, p.scope
        ));
    }
    code.push_str("];\n");

    code.push_str("// --- git_guard_resource_limits.yaml ---\n");
    code.push_str(&format!(
        "pub const NOFILE_LIMIT: u64 = {};\n",
        nofile_limit
    ));

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("shell_guard_config.rs"), code).unwrap();

    println!("cargo:rerun-if-changed=config/shell_guard_policy.yaml");
    println!("cargo:rerun-if-changed=config/shell_guard_policy_matrix.yaml");
    println!("cargo:rerun-if-changed=config/git_guard_resource_limits.yaml");
}
