// Binary-guard codegen for build.rs (feature `binary-guard`).
//
// These structs are ONLY used to deserialize res/binary-lock.yaml into a
// form that can be emitted as a const literal. The runtime structs
// (BinaryPolicy, RejectRule, RejectKind) live in src/binary_policy_types.rs
// and are never emitted. The generated file contains ONLY the
// `pub const BINARY_POLICIES: &[BinaryPolicy] = &[ ... ];` literal plus the
// sorted BINARY_POLICY_ALIASES index.

use std::env;
use std::fs;
use std::path::Path;

use serde::Deserialize;

#[derive(Deserialize)]
struct BinaryLockFile {
    #[serde(default = "crate::default_version")]
    _version: u32,
    binaries: Vec<BinaryLockEntry>,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct BinaryLockEntry {
    name: String,
    #[serde(default)]
    tags: Vec<String>,
    #[serde(default)]
    path: Option<String>,
    #[serde(default)]
    contained: bool,
    policy: String,
    #[serde(default)]
    allow_subcommands: Vec<String>,
    #[serde(default)]
    allow_self_username: bool,
    #[serde(default)]
    reject_patterns: Vec<RejectPatternYaml>,
    #[serde(default)]
    env_sanitise: Vec<String>,
}

#[derive(Deserialize)]
struct RejectPatternYaml {
    kind: String,
    #[serde(default)]
    flag: Option<String>,
    #[serde(default)]
    pattern: Option<String>,
    #[serde(default)]
    subcommand: Option<String>,
    #[serde(default)]
    requires_flags: Vec<String>,
    reason: String,
}

/// Emit OUT_DIR/binary_policies.rs containing ONLY the
/// `pub const BINARY_POLICIES: &[BinaryPolicy] = &[ ... ];` literal plus the
/// sorted BINARY_POLICY_ALIASES index (F15).
///
/// The structs the literal references (BinaryPolicy, RejectRule, RejectKind)
/// are defined in hand-written src/binary_policy_types.rs. build.rs emits
/// no type definitions and no function bodies: baking logic into generated
/// strings breaks IDE support and diffs readably; the codegen smell this
/// split is designed to prevent.
pub fn emit_binary_guard_config(manifest: &Path) {
    let res_dir = manifest.join("res");
    let lock_path = res_dir.join("binary-lock.yaml");
    let text = fs::read_to_string(&lock_path).unwrap_or_else(|e| {
        panic!(
            "build.rs: failed to read {}: {}. Run `make sync-gtfobins` to regenerate. {}",
            lock_path.display(),
            e,
            "res/binary-lock.yaml is the generated build input for the binary guard.",
        )
    });
    let lock: BinaryLockFile = serde_yaml::from_str(&text)
        .unwrap_or_else(|e| panic!("build.rs: failed to parse {}: {}", lock_path.display(), e));

    // F15: the policy table is emitted sorted by name so the runtime
    // lookup is a binary search. Duplicate names or alias collisions
    // would make binary search ambiguous, so both are build-fatal.
    let mut sorted: Vec<&BinaryLockEntry> = lock.binaries.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    for w in sorted.windows(2) {
        if w[0].name == w[1].name {
            panic!(
                "build.rs: duplicate binary name {:?} in res/binary-lock.yaml",
                w[0].name
            );
        }
    }
    {
        let mut names: std::collections::HashSet<&str> =
            sorted.iter().map(|b| b.name.as_str()).collect();
        for b in &sorted {
            for a in &b.allow_subcommands {
                if *a != b.name && !names.insert(a.as_str()) {
                    panic!(
                        "build.rs: alias {:?} on {:?} collides with another name/alias in res/binary-lock.yaml",
                        a, b.name
                    );
                }
            }
        }
    }

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs from res/binary-lock.yaml. DO NOT EDIT.\n");
    code.push_str("// Run `make sync-gtfobins` to regenerate. This file contains ONLY the\n");
    code.push_str("// BINARY_POLICIES const literal; the structs it references live in\n");
    code.push_str(
        "// src/binary_policy_types.rs (hand-written). build.rs emits no fn/struct/enum.\n\n",
    );
    code.push_str("// BINARY_POLICIES is sorted by name (binary-searchable).\n");
    code.push_str("pub const BINARY_POLICIES: &[BinaryPolicy] = &[\n");
    for b in &sorted {
        code.push_str("    BinaryPolicy {\n");
        code.push_str(&format!("        name: {:?},\n", b.name));
        code.push_str(&format!("        policy: {},\n", policy_variant(&b.policy)));
        code.push_str("        allow_subcommands: &[");
        emit_str_literals_inline(&mut code, &b.allow_subcommands);
        code.push_str("],\n");
        code.push_str(&format!(
            "        allow_self_username: {},\n",
            b.allow_self_username
        ));
        code.push_str("        reject_patterns: &[\n");
        for rp in &b.reject_patterns {
            code.push_str("            RejectRule {\n");
            code.push_str(&format!(
                "                kind: {},\n",
                reject_kind_variant(&rp.kind)
            ));
            match &rp.flag {
                Some(f) => code.push_str(&format!("                flag: Some({:?}),\n", f)),
                None => code.push_str("                flag: None,\n"),
            }
            match &rp.pattern {
                Some(p) => code.push_str(&format!("                pattern: Some({:?}),\n", p)),
                None => code.push_str("                pattern: None,\n"),
            }
            match &rp.subcommand {
                Some(s) => code.push_str(&format!("                subcommand: Some({:?}),\n", s)),
                None => code.push_str("                subcommand: None,\n"),
            }
            code.push_str("                requires_flags: &[");
            emit_str_literals_inline(&mut code, &rp.requires_flags);
            code.push_str("],\n");
            code.push_str(&format!("                reason: {:?},\n", rp.reason));
            code.push_str("            },\n");
        }
        code.push_str("        ],\n");
        code.push_str("        env_sanitise: &[");
        emit_str_literals_inline(&mut code, &b.env_sanitise);
        code.push_str("],\n");
        code.push_str("    },\n");
    }
    code.push_str("];\n\n");

    // Alias index: (alias, policy-index) pairs sorted by alias so the
    // symlink-alias lookup is a binary search instead of a second linear
    // scan with per-entry `contains` (F15). Uniqueness verified above.
    let mut alias_pairs: Vec<(&str, usize)> = Vec::new();
    for (idx, b) in sorted.iter().enumerate() {
        for a in &b.allow_subcommands {
            if *a != b.name {
                alias_pairs.push((a.as_str(), idx));
            }
        }
    }
    alias_pairs.sort_by(|a, b| a.0.cmp(b.0));
    code.push_str("// (alias, BINARY_POLICIES index) sorted by alias.\n");
    code.push_str("pub const BINARY_POLICY_ALIASES: &[(&str, u32)] = &[\n");
    for (alias, idx) in alias_pairs {
        code.push_str(&format!("    ({:?}, {}),\n", alias, idx));
    }
    code.push_str("];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("binary_policies.rs"), code).unwrap();
    println!("cargo:rerun-if-changed=res/binary-lock.yaml");
}

fn emit_str_literals_inline(buf: &mut String, items: &[String]) {
    for (i, item) in items.iter().enumerate() {
        if i > 0 {
            buf.push_str(", ");
        }
        buf.push_str(&format!("{:?}", item));
    }
}

/// Map a policy string from the YAML into the enum variant identifier emitted
/// in the generated const literal. A const context cannot call `from_str`, so
/// build.rs converts the wire string to the variant path at codegen time.
/// Panics on an unknown policy string (fail-closed at build time, not runtime).
fn policy_variant(s: &str) -> &'static str {
    match s {
        "deny-non-root" => "PolicyKind::DenyNonRoot",
        "deny-all-non-root" => "PolicyKind::DenyAllNonRoot",
        "arg-validate" => "PolicyKind::ArgValidate",
        "pass-through" => "PolicyKind::PassThrough",
        other => panic!(
            "build.rs: unknown policy string {:?} in res/binary-lock.yaml",
            other
        ),
    }
}

/// Map a reject-kind string from the YAML into the enum variant identifier.
fn reject_kind_variant(s: &str) -> &'static str {
    match s {
        "flag" => "RejectKind::Flag",
        "regex" => "RejectKind::Regex",
        other => panic!(
            "build.rs: unknown reject kind {:?} in res/binary-lock.yaml",
            other
        ),
    }
}
