// Top-level package build script (non-privileged tools).
//
// Compiles the shell-guard policy, binary-guard policy, and git-ssh
// allowlist into generated constants for their respective bin roots. The
// privileged Git guard has its own package (git-guard/) and build script;
// no git-guard module enters this package's dependency closure.

use std::env;
use std::fs;
use std::os::unix::fs::MetadataExt;
use std::path::Path;

use serde::de::DeserializeOwned;
use serde::Deserialize;

mod build_binary_guard;
mod build_shell_guard;

pub(crate) fn default_version() -> u32 {
    1
}

#[derive(Deserialize)]
struct GitSshAllowlistConfig {
    #[serde(default = "default_version")]
    _version: u32,
    hosts: Vec<String>,
    users: Vec<String>,
}

fn valid_host_or_user(s: &str) -> bool {
    !s.is_empty()
        && s.chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '_' || c == '-')
}

#[derive(Deserialize)]
struct ResourceLimitsConfig {
    #[serde(default = "default_version")]
    _version: u32,
    nofile: u64,
}

fn read_yaml<T: DeserializeOwned>(config_dir: &Path, name: &str) -> T {
    let path = config_dir.join(name);
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("build.rs: failed to read {}: {}", path.display(), e));
    serde_yaml::from_str(&text)
        .unwrap_or_else(|e| panic!("build.rs: failed to parse {}: {}", path.display(), e))
}

fn emit_str_list(buf: &mut String, name: &str, items: &[String]) {
    if items.is_empty() {
        buf.push_str(&format!("pub const {}: &[&str] = &[];\n", name));
        return;
    }
    buf.push_str(&format!("pub const {}: &[&str] = &[\n", name));
    for item in items {
        buf.push_str(&format!("    {:?},\n", item));
    }
    buf.push_str("];\n\n");
}

/// Fail-closed provenance backstop: refuse to compile when a policy config
/// compiled into a privileged binary is not owned by uid 0. An agent-owned
/// config would let the agent rewrite guard policy and rebuild.
fn check_config_provenance(config_dir: &Path, files: &[&str]) {
    let mut offenders: Vec<String> = Vec::new();
    for name in files {
        let path = config_dir.join(name);
        match fs::metadata(&path) {
            Ok(meta) if meta.uid() == 0 => {}
            Ok(meta) => offenders.push(format!("{} (uid {})", path.display(), meta.uid())),
            Err(e) => offenders.push(format!("{} (unreadable: {})", path.display(), e)),
        }
    }
    if !offenders.is_empty() {
        panic!(
            "build.rs: refusing to compile: guard policy configs not owned by uid 0:\n  {}\n\
             Repair ownership via the operator relock path (see AGENTS.md).",
            offenders.join("\n  ")
        );
    }
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let config_dir = Path::new(&manifest).join("config");

    let config_files = [
        "git_ssh_allowlist.yaml",
        "git_guard_resource_limits.yaml",
        "shell_guard_policy.yaml",
        "shell_guard_policy_matrix.yaml",
    ];
    check_config_provenance(&config_dir, &config_files);

    let ssh_allowlist: GitSshAllowlistConfig = read_yaml(&config_dir, "git_ssh_allowlist.yaml");
    if ssh_allowlist.hosts.is_empty() || ssh_allowlist.users.is_empty() {
        panic!("build.rs: git_ssh_allowlist.yaml needs non-empty hosts and users");
    }
    for entry in ssh_allowlist.hosts.iter().chain(ssh_allowlist.users.iter()) {
        if !valid_host_or_user(entry) {
            panic!("build.rs: git_ssh_allowlist.yaml bad entry {:?}", entry);
        }
    }
    let limits: ResourceLimitsConfig = read_yaml(&config_dir, "git_guard_resource_limits.yaml");

    let out_dir = env::var("OUT_DIR").unwrap();
    let mut ssh_code =
        String::from("// Auto-generated by build.rs from config/git_ssh_allowlist.yaml.\n");
    emit_str_list(&mut ssh_code, "GIT_SSH_ALLOWED_HOSTS", &ssh_allowlist.hosts);
    emit_str_list(&mut ssh_code, "GIT_SSH_ALLOWED_USERS", &ssh_allowlist.users);
    fs::write(Path::new(&out_dir).join("git_ssh_config.rs"), ssh_code).unwrap();

    for name in &config_files {
        println!("cargo:rerun-if-changed=config/{}", name);
    }

    // Binary-guard codegen. Gated on the cargo feature so the default
    // build does not require res/binary-lock.yaml to exist. Emits ONLY the
    // BINARY_POLICIES const literal; no struct/fn/enum.
    if env::var_os("CARGO_FEATURE_BINARY_GUARD").is_some() {
        build_binary_guard::emit_binary_guard_config(Path::new(&manifest));
    }

    build_shell_guard::emit_shell_guard_config(Path::new(&manifest), limits.nofile);
}
