#!/usr/bin/env bash
# generate-hooks — Generate native git hooks for ami-git-guard.
# Zero-dependency bash alternative to the pre-commit Python framework.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GIT_DIR="$(cd "$REPO_ROOT" && git rev-parse --git-dir)"
HOOK_DIR="$GIT_DIR/hooks"

mkdir -p "$HOOK_DIR"

# ── Common header for all hooks ───────────────────────────────────────────
_header() {
    cat << 'EOF'
#!/usr/bin/env bash
# AUTO-GENERATED by scripts/generate-hooks — do not edit.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

# Dynamically discover .boot-linux by walking up from repo root.
# If not found, fall back to system toolchain.
BOOT_LINUX=""
dir="$ROOT"
while [[ "$dir" != "/" ]]; do
    if [[ -d "$dir/.boot-linux/bin" ]]; then
        BOOT_LINUX="$dir/.boot-linux"
        break
    fi
    dir="$(dirname "$dir")"
done

if [[ -n "$BOOT_LINUX" ]]; then
    export RUSTUP_HOME="$BOOT_LINUX/rust"
    export CARGO_HOME="$BOOT_LINUX/rust"
    # System PATH first so gcc finds system ld (not musl ld from .boot-linux)
    export PATH="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:$BOOT_LINUX/bin"
else
    # Fall back to system toolchain
    export PATH="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"
fi

# Use system gcc to avoid musl cross-compiler contamination
export CC=/usr/bin/gcc
export RUSTFLAGS="-C linker=/usr/bin/gcc"

EOF
}

# ── pre-commit ────────────────────────────────────────────────────────────
{
    _header
    cat << 'EOF'
# Only run Rust checks when Rust files are staged
STAGED="$(git diff --cached --name-only --diff-filter=ACMR || true)"
MATCH="$(echo "$STAGED" | grep -E '\.rs$|Cargo\.toml$|Cargo\.lock$' || true)"

if [[ -z "$MATCH" ]]; then
    echo "cargo hooks: no Rust files staged — skipping"
    exit 0
fi

echo ""
echo "Running: cargo fmt..."
cargo fmt --check

echo ""
echo "Running: cargo build..."
cargo build

echo ""
echo "Running: cargo clippy..."
cargo clippy -- -D warnings

echo ""
echo "All pre-commit hooks passed."
EOF
} > "$HOOK_DIR/pre-commit"
chmod +x "$HOOK_DIR/pre-commit"
echo "Generated $HOOK_DIR/pre-commit"

# ── pre-push ──────────────────────────────────────────────────────────────
{
    _header
    cat << 'EOF'
echo ""
echo "Running: cargo test..."
cargo test

echo ""
echo "All pre-push hooks passed."
EOF
} > "$HOOK_DIR/pre-push"
chmod +x "$HOOK_DIR/pre-push"
echo "Generated $HOOK_DIR/pre-push"

echo ""
echo "Native git hooks installed."
