use super::*;
use std::os::unix::fs::PermissionsExt;

fn unique_temp_dir(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "guard-ci-integrity-test-{}-{}-{}",
        tag,
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir_all(&dir).unwrap();
    dir
}

fn run_git(dir: &Path, args: &[&str]) -> bool {
    std::process::Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(args)
        .env("GIT_CONFIG_COUNT", "1")
        .env("GIT_CONFIG_KEY_0", "safe.directory")
        .env("GIT_CONFIG_VALUE_0", "*")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn init_repo(dir: &Path) {
    fs::create_dir_all(dir).unwrap();
    fs::create_dir_all(dir.join(".git")).unwrap();
    fs::write(
        dir.join(".git/config"),
        "[user]\n\temail = t@t\n\tname = t\n",
    )
    .unwrap();
    assert!(run_git(dir, &["init", "-q"]));
    fs::write(dir.join("f.txt"), "x").unwrap();
    assert!(run_git(dir, &["add", "f.txt"]));
    assert!(run_git(dir, &["commit", "-qm", "init"]));
}

fn write_hook(dir: &Path, name: &str, executable: bool, marker: bool) {
    let hooks = dir.join("hooks");
    fs::create_dir_all(&hooks).unwrap();
    let body = if marker {
        "#!/bin/bash\n# AUTO-GENERATED by generate-hooks\nexit 0\n"
    } else {
        "#!/bin/bash\nexit 0\n"
    };
    let path = hooks.join(name);
    fs::write(&path, body).unwrap();
    let mode = if executable { 0o755 } else { 0o644 };
    fs::set_permissions(&path, fs::Permissions::from_mode(mode)).unwrap();
}

#[test]
fn hook_missing_is_violation() {
    let dir = unique_temp_dir("hook-missing");
    let reason = hook_violation_reason(&dir.join("nope")).unwrap();
    assert!(reason.contains("missing"), "unexpected: {}", reason);
}

#[test]
fn hook_not_executable_is_violation() {
    let dir = unique_temp_dir("hook-noexec");
    write_hook(&dir, "pre-commit", false, true);
    let reason = hook_violation_reason(&dir.join("hooks/pre-commit")).unwrap();
    assert!(reason.contains("not executable"), "unexpected: {}", reason);
}

#[test]
fn hook_without_marker_is_violation() {
    let dir = unique_temp_dir("hook-nomarker");
    write_hook(&dir, "pre-commit", true, false);
    let reason = hook_violation_reason(&dir.join("hooks/pre-commit")).unwrap();
    assert!(reason.contains("marker"), "unexpected: {}", reason);
}

#[test]
fn valid_hook_passes() {
    let dir = unique_temp_dir("hook-ok");
    write_hook(&dir, "pre-commit", true, true);
    assert!(hook_violation_reason(&dir.join("hooks/pre-commit")).is_none());
}

#[test]
fn consumer_hooks_all_present_passes() {
    let dir = unique_temp_dir("consumer-ok");
    for hook in REQUIRED_HOOKS {
        write_hook(&dir.join(".git"), hook, true, true);
    }
    init_repo(&dir);
    assert!(check_consumer_hooks(dir.to_str().unwrap()).is_ok());
}

#[test]
fn consumer_hooks_missing_fails_closed() {
    let dir = unique_temp_dir("consumer-missing");
    init_repo(&dir);
    let err = check_consumer_hooks(dir.to_str().unwrap()).unwrap_err();
    let msg = format!("{:?}", err);
    assert!(msg.contains("pre-commit"), "unexpected: {}", msg);
    assert!(msg.contains("commit-msg"), "unexpected: {}", msg);
    assert!(msg.contains("pre-push"), "unexpected: {}", msg);
}

#[test]
fn parse_ls_files_extracts_mode_and_path() {
    let blob = "100755 abc 0\tscripts/foo\u{0}100644 def 0\tREADME.md\u{0}";
    let entries = parse_ls_files(blob);
    assert_eq!(entries.len(), 2);
    assert_eq!(
        entries[0],
        ("100755".to_string(), "scripts/foo".to_string())
    );
    assert_eq!(entries[1], ("100644".to_string(), "README.md".to_string()));
}

#[test]
fn deployment_clean_repo_has_no_violations() {
    let dir = unique_temp_dir("deploy-clean");
    init_repo(&dir);
    let uid = nix::unistd::geteuid().as_raw();
    let violations = deployment_violations(&dir, 0, uid, false);
    assert!(violations.is_empty(), "unexpected: {:?}", violations);
}

#[test]
fn divergence_ahead_is_violation() {
    let v = divergence_violation(Path::new("/x"), "aaa", "bbb", 2).unwrap();
    assert!(v.contains("ahead of origin/main"), "unexpected: {}", v);
}

#[test]
fn divergence_clean_is_none() {
    assert!(divergence_violation(Path::new("/x"), "aaa", "aaa", 0).is_none());
}

#[test]
fn divergence_behind_warns_but_passes() {
    assert!(divergence_violation(Path::new("/x"), "aaa", "bbb", 0).is_none());
}

#[test]
fn deployment_wrong_owner_is_violation() {
    let dir = unique_temp_dir("deploy-owner");
    init_repo(&dir);
    let wrong_uid = nix::unistd::geteuid().as_raw() + 1;
    // .git is root-locked by the guard; wrong file uid still flags tracked files.
    let violations = deployment_violations(&dir, wrong_uid, wrong_uid, false);
    assert!(
        violations.iter().any(|v| v.contains(".git owned by uid")),
        "unexpected: {:?}",
        violations
    );
}

#[test]
fn deployment_exec_bit_mismatch_is_violation() {
    let dir = unique_temp_dir("deploy-exec");
    init_repo(&dir);
    let script = dir.join("tool.sh");
    fs::write(&script, "#!/bin/bash\n").unwrap();
    fs::set_permissions(&script, fs::Permissions::from_mode(0o755)).unwrap();
    assert!(run_git(&dir, &["add", "tool.sh"]));
    assert!(run_git(&dir, &["commit", "-qm", "add tool"]));
    fs::set_permissions(&script, fs::Permissions::from_mode(0o644)).unwrap();
    let uid = nix::unistd::geteuid().as_raw();
    let violations = deployment_violations(&dir, 0, uid, false);
    assert!(
        violations.iter().any(|v| v.contains("100755")),
        "unexpected: {:?}",
        violations
    );
}
