# fake_repo.bash: build a throwaway mini-repo that mirrors the
# WORKSPACE-GUARD layout (scripts/, scripts/lib/, config/, res/,
# docs/references/) so scripts that resolve REPO_ROOT from their own
# BASH_SOURCE location can run against controlled fixtures instead of
# the live repo.
#
#   make_fake_repo            -> echoes the new repo dir path
#   copy_real_scripts <dir>    -> copies scripts/ and scripts/lib/ from
#                                the live repo into the fake repo
#   fake_binaries_yaml <dir> <list...> -> write a minimal
#                                res/binary-lock.yaml listing the
#                                given absolute paths as lock surface
#
# The fake repo lives under $TEST_TMPDIR (set up by harness setup) and
# is wiped by teardown. Scripts copied in are byte-identical to the
# live ones so the test exercises the real code paths.

copy_real_scripts() {
    local dir="$1"
    mkdir -p "$dir/scripts/lib"
    cp "$GUARD_ROOT/scripts/sync-gtfobins"        "$dir/scripts/sync-gtfobins"
    cp "$GUARD_ROOT/scripts/suid-drift-check"     "$dir/scripts/suid-drift-check"
    cp "$GUARD_ROOT/scripts/regen-gitleaksignore" "$dir/scripts/regen-gitleaksignore"
    cp "$GUARD_ROOT/scripts/install-lock-runtime" "$dir/scripts/install-lock-runtime"
    cp "$GUARD_ROOT/scripts/uninstall-lock-runtime" "$dir/scripts/uninstall-lock-runtime"
    cp "$GUARD_ROOT/scripts/lib/"*.sh "$dir/scripts/lib/"
    chmod +x "$dir/scripts/"*
}

# Emit a minimal binary-lock.yaml with the given paths as the lock
# surface. Each path becomes a sequence entry with name, path, and a
# deny-non-root policy. install-lock-runtime's awk parser reads only
# the `path:` fields that are not null.
fake_binaries_yaml() {
    local dir="$1"; shift
    local p bname
    mkdir -p "$dir/res"
    {
        echo "# Auto-generated by tests/shell/lib/fake_repo.bash"
        echo "version: 1"
        echo "binaries:"
        for p in "$@"; do
            bname="$(basename "$p")"
            printf '  - name: "%s"\n' "$bname"
            printf '    tags: ["suid"]\n'
            printf '    path: "%s"\n' "$p"
            printf '    contained: false\n'
            printf '    policy: deny-non-root\n'
            printf '    allow_subcommands: []\n'
            printf '    allow_self_username: false\n'
            printf '    env_sanitise: ["LD_PRELOAD", "LD_LIBRARY_PATH"]\n'
            printf '    reject_patterns: []\n'
            printf '\n'
        done
    } > "$dir/res/binary-lock.yaml"
}

# Create fake SUID host binaries (regular files) inside the fake repo
# so install-lock-runtime has real targets to seal. Each path's parent
# dir is created. Emits a small binary that responds to --version.
make_fake_suid() {
    local dir="$1"; shift
    local p parent
    for p in "$@"; do
        parent="$(dirname "$p")"
        mkdir -p "$parent"
        {
            echo '#!/usr/bin/env bash'
            echo 'echo "fake: '"$p"' 1.0"'
        } > "$p"
        chmod 4755 "$p"
    done
}

make_fake_repo() {
    local dir="$TEST_TMPDIR/repo"
    mkdir -p "$dir/res" "$dir/docs/references"
    echo "$dir"
}

# Stage a fake reference HTML so sync-gtfobins can parse without
# network. The body is a minimal GTFOBins-shaped page with a handful
# of data-gtfobin-name rows carrying SUID/Sudo/Capabilities contexts.
fake_gtfobins_html() {
    local file="$1"; shift
    mkdir -p "$(dirname "$file")"
    {
        echo '<html><body><table>'
        local name ctxs
        for pair in "$@"; do
            name="${pair%%:*}"
            ctxs="${pair#*:}"
            printf '<tr data-gtfobin-name="%s">' "$name"
            printf '<td data-function-contexts="%s"></td>' "$ctxs"
            printf '</tr>\n'
        done
        echo '</table></body></html>'
    } > "$file"
}

# Plain-text SUID list (konstruktoid shape): one binary name per line,
# comments allowed.
fake_konstruktoid_list() {
    local file="$1"; shift
    mkdir -p "$(dirname "$file")"
    printf '%s\n' "$@" > "$file"
}