# fake_repo.bash: build a throwaway mini-repo that mirrors the
# WORKSPACE-GUARD layout (scripts/, scripts/lib/, config/, res/,
# docs/references/) so scripts that resolve REPO_ROOT from their own
# BASH_SOURCE location can run against controlled fixtures instead of
# the live repo.
#
#   make_fake_repo            -> echoes the new repo dir path
#   copy_real_scripts <dir>    -> copies scripts/ and scripts/lib/ from
#                                the live repo into the fake repo
#   fake_binaries_yaml <dir> <list...> -> write a minimal
#                                res/binary-lock.yaml listing the
#                                given absolute paths as lock surface
#
# The fake repo lives under $TEST_TMPDIR (set up by harness setup) and
# is wiped by teardown. Scripts copied in are byte-identical to the
# live ones so the test exercises the real code paths.

copy_real_scripts() {
    local dir="$1"
    mkdir -p "$dir/scripts/lib"
    cp "$GUARD_ROOT/scripts/sync-gtfobins"        "$dir/scripts/sync-gtfobins"
    cp "$GUARD_ROOT/scripts/suid-drift-check"     "$dir/scripts/suid-drift-check"
    cp "$GUARD_ROOT/scripts/install-home-lock"    "$dir/scripts/install-home-lock"
    cp "$GUARD_ROOT/scripts/uninstall-home-lock"  "$dir/scripts/uninstall-home-lock"
    cp "$GUARD_ROOT/scripts/home-drift-check"     "$dir/scripts/home-drift-check"
    cp "$GUARD_ROOT/scripts/regen-gitleaksignore" "$dir/scripts/regen-gitleaksignore"
    cp "$GUARD_ROOT/scripts/install-lock-runtime" "$dir/scripts/install-lock-runtime"
    cp "$GUARD_ROOT/scripts/uninstall-lock-runtime" "$dir/scripts/uninstall-lock-runtime"
    cp "$GUARD_ROOT/scripts/lib/"*.sh "$dir/scripts/lib/"
    chmod +x "$dir/scripts/"*
}

# Copy config/binary-policy-rules.yaml into the fake repo so
# emit_binary_lock (sourced from scripts/lib/binary-lock-yaml.sh) can
# join rules against the universe. Also creates config/ if absent.
copy_real_config() {
    local dir="$1"
    mkdir -p "$dir/config"
    cp "$GUARD_ROOT/config/binary-policy-rules.yaml" "$dir/config/"
}

# Stage a fake guard binary at $dir/target/release/workspace-binary-guard
# so install-lock-runtime's GUARD_BIN preflight passes. The fake binary
# contains the "workspace-guard" sentinel string (used by rollback_path
# and idempotency checks) and responds to --version / --help.
fake_guard_binary() {
    local dir="$1"
    mkdir -p "$dir/target/release"
    local gb="$dir/target/release/workspace-binary-guard"
    cat > "$gb" <<'GUARDEOF'
#!/usr/bin/env bash
# workspace-guard sentinel marker
case "${1:-}" in
    --version) echo "workspace-binary-guard 0.1.0 (fake)"; exit 0 ;;
    --help)    echo "workspace-binary-guard (fake)"; exit 0 ;;
esac
exit 0
GUARDEOF
    chmod 0755 "$gb"
}

# Emit a minimal binary-lock.yaml with the given paths as the lock
# surface. Each path becomes a sequence entry with name, path, and a
# deny-non-root policy. install-lock-runtime's awk parser reads only
# the `path:` fields that are not null.
fake_binaries_yaml() {
    local dir="$1"; shift
    local p bname
    mkdir -p "$dir/res"
    {
        echo "# Auto-generated by tests/shell/lib/fake_repo.bash"
        echo "version: 1"
        echo "binaries:"
        for p in "$@"; do
            bname="$(basename "$p")"
            printf '  - name: "%s"\n' "$bname"
            printf '    tags: ["suid"]\n'
            printf '    path: "%s"\n' "$p"
            printf '    contained: false\n'
            printf '    policy: deny-non-root\n'
            printf '    allow_subcommands: []\n'
            printf '    allow_self_username: false\n'
            printf '    env_sanitise: ["LD_PRELOAD", "LD_LIBRARY_PATH"]\n'
            printf '    reject_patterns: []\n'
            printf '\n'
        done
    } > "$dir/res/binary-lock.yaml"
}

# Create fake SUID host binaries (regular files) inside the fake repo
# so install-lock-runtime has real targets to seal. Each path's parent
# dir is created. Emits a small binary that responds to --version.
make_fake_suid() {
    local dir="$1"; shift
    local p parent
    for p in "$@"; do
        parent="$(dirname "$p")"
        mkdir -p "$parent"
        {
            echo '#!/usr/bin/env bash'
            echo 'echo "fake: '"$p"' 1.0"'
        } > "$p"
        chmod 4755 "$p"
    done
}

make_fake_repo() {
    local dir="$TEST_TMPDIR/repo"
    mkdir -p "$dir/res" "$dir/docs/references"
    echo "$dir"
}

# Stage a fake reference HTML so sync-gtfobins can parse without
# network. The body is a minimal GTFOBins-shaped page with a handful
# of data-gtfobin-name rows carrying SUID/Sudo/Capabilities contexts.
fake_gtfobins_html() {
    local file="$1"; shift
    mkdir -p "$(dirname "$file")"
    {
        echo '<html><body><table>'
        local name ctxs
        for pair in "$@"; do
            name="${pair%%:*}"
            ctxs="${pair#*:}"
            printf '<tr data-gtfobin-name="%s">' "$name"
            printf '<td data-function-contexts="%s"></td>' "$ctxs"
            printf '</tr>\n'
        done
        echo '</table></body></html>'
    } > "$file"
}

# Plain-text SUID list (konstruktoid shape): one binary name per line,
# comments allowed.
fake_konstruktoid_list() {
    local file="$1"; shift
    mkdir -p "$(dirname "$file")"
    printf '%s\n' "$@" > "$file"
}

# Copy config/guard_locked_paths.yaml into the fake repo so install-
# home-lock can read the absolute_file_paths block. Also copies the
# real config dir if absent. Tests can later overwrite the YAML.
copy_real_locked_paths() {
    local dir="$1"
    mkdir -p "$dir/config"
    cp "$GUARD_ROOT/config/guard_locked_paths.yaml" "$dir/config/" 2>"$DEVNULL" || true
}

# Write a minimal fake /etc/passwd file at $1 with one user row. The
# row maps the user's home dir so install-home-lock straceability
# tests under WORKSPACE_PASSWD_FILE get a deterministic uid/gid. Most
# tests just need a fake passwd that exists; the install-home-lock
# script does not actually read /etc/passwd for the chown path
# (chown root:root is unconditional), but the env var is reserved
# for future entries that may need ~user resolution.
fake_passwd() {
    local file="$1"; shift
    local user="${1:-agent}" uid="${2:-1000}" gid="${3:-1000}" home="${4:-$TEST_TMPDIR/fakehome}"
    mkdir -p "$(dirname "$file")"
    {
        echo "root:x:0:0:root:$home:/bin/bash"
        echo "$user:x:$uid:$gid:$user:$home:/bin/bash"
    } > "$file"
}

# Materialize a fake home tree at $1 with empty .gitconfig, .ssh/,
# .config/git/ files. Non-existent paths become empty files so install-
# home-lock's create-missing branch can be exercised by tests that
# delete the tree first.
fake_home_tree() {
    local dir="$1"
    mkdir -p "$dir/.ssh" "$dir/.config/git"
    touch "$dir/.gitconfig" "$dir/.gitconfig.local" \
          "$dir/.config/git/config" \
          "$dir/.ssh/authorized_keys" "$dir/.ssh/config"
}

# Assert $1 (state file) has a path entry for $2 with the given mode.
# Returns 0/1 (no output) so tests can `[ assert_home_state_entry ... ]`.
assert_home_state_entry() {
    local state="$1" path="$2" mode="${3:-}"
    [ -f "$state" ] || return 1
    grep -q "path: \"$path\"" "$state" || return 1
    if [ -n "$mode" ]; then
        grep -q "expected_mode: \"$mode\"" "$state" || return 1
    fi
    return 0
}